import type {Metadata} from "next";
import Link from "next/link";
import { consciousnessPublication as publication } from "@/config/consciousness";
import { site } from "@/config/site";
import { listConsciousnessDocuments, getConsciousnessTotals } from "@/lib/consciousness";
import ConsciousnessSearch from "@/components/consciousness-search";
export const dynamic="force-static";
export const metadata:Metadata={title:"Shadow Theory and Consciousness · Complete Monograph",description:publication.description,alternates:{canonical:"/consciousness/monograph",types:{"text/markdown":publication.markdownUrl}},openGraph:{title:publication.title,url:"/consciousness/monograph",type:"book",images:["/publications/consciousness/social.png"]}};
export default function MonographPage(){
  const documents=listConsciousnessDocuments();const totals=getConsciousnessTotals();
  const groups=new Map<string,typeof documents>();
  const partTitles = new Map(documents.filter(d=>d.partTitle).map(d=>[d.part,d.partTitle]));
  for(const document of documents){const key=document.kind==="appendix"?"Technical appendices":document.kind==="bibliography"?"Bibliography":document.part?`Part ${document.part} — ${partTitles.get(document.part) || ""}`:"Front matter"; groups.set(key,[...(groups.get(key)||[]),document]);}
  return <article className="c-book"><nav className="quantum-reader-breadcrumb" aria-label="Breadcrumb"><Link href="/consciousness">Consciousness</Link><span>/</span><span aria-current="page">Complete monograph</span></nav><header className="c-book-cover"><p className="c-eyebrow">The complete web edition / SPC-2</p><h1>Shadow Theory<br/>and <em>Consciousness.</em></h1><p className="c-book-subtitle">Awareness, Perspectival Realization,<br/>and the Source-to-Experience Problem</p><div className="c-book-byline"><p>Jeremy Rodgers<br/><span>Independent Researcher</span></p><p>Version 2 — publication edition<br/><span>20 September 2026</span></p></div><div className="c-actions"><Link className="c-button c-button-primary" href="/consciousness/monograph/preface-and-scope">Begin reading ↗</Link><a className="c-button" href="#contents">Browse the contents ↓</a></div><p className="c-book-doi"><a href={publication.doiUrl}>doi:{publication.doi} ↗</a></p><div className="c-book-orbits" aria-hidden="true"><i/><i/><i/><span>A0 · A1 · A2 · A3</span></div></header>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Book",name:publication.title,description:publication.description,author:{"@type":"Person",name:publication.author},bookEdition:"Version 2 — publication edition",datePublished:publication.published,url:`${site.url}${publication.webUrl}`,identifier:publication.doiUrl,inLanguage:"en",hasPart:documents.map(d=>({"@type":"Chapter",name:d.title,position:d.order,url:`${site.url}${d.url}`})),encoding:[{format:"application/pdf",url:publication.pdfUrl},{format:"text/markdown",url:publication.markdownUrl},{format:"application/x-tex",url:publication.texUrl}].map(e=>({"@type":"MediaObject",encodingFormat:e.format,contentUrl:`${site.url}${e.url}`}))})}}/>
    <div className="c-book-intro"><div><h2>A complete argument, open to inspection.</h2><p>From the source-to-experience question to realized vessels, four constitutive laws, a finite completion theorem, and its implications for human and artificial experience. Read every statement, calculation and proof in the publication.</p><p>The physical constructions retain their own assumptions. The psychophysical result is conditional on certified realization and SPC-2; independent realization and phenomenal validation remain open.</p></div><aside><dl><div><dt>Chapters</dt><dd>{totals.chapters}</dd></div><div><dt>Appendices</dt><dd>{totals.appendices}</dd></div><div><dt>Proofs</dt><dd>{totals.proofs}</dd></div><div><dt>References</dt><dd>{totals.references}</dd></div></dl><a href={publication.pdfUrl}>Publication PDF ↗</a><a href={publication.markdownUrl}>Complete book Markdown ↗</a><a href={publication.texUrl}>Original LaTeX source ↗</a></aside></div>
    <nav className="c-reading-paths" aria-label="Suggested reading paths"><Link href="/consciousness/monograph/the-source-to-experience-problem"><span>01 / Understand the idea</span><strong>Awareness and a lived world</strong><p>Chapters 1–4, then 17, 21, 24 and 25.</p></Link><Link href="/consciousness/monograph/why-a-manifestation-law-is-additional"><span>02 / Inspect the constitution</span><strong>The complete formal argument</strong><p>Chapters 14–20 and Appendices B, D and F.</p></Link><Link href="/consciousness/monograph/biological-and-comparative-applications"><span>03 / Follow the implications</span><strong>Brains, identity and artificial systems</strong><p>Chapters 2, 17 and 20–24.</p></Link></nav>
    <section id="contents" className="c-book-contents"><div className="c-section-heading"><div><p className="c-eyebrow">5 parts / {totals.sections} sections</p><h2>The complete contents.</h2></div><a href="/consciousness/manifest.json">Machine-readable inventory ↗</a></div><ConsciousnessSearch/>{Array.from(groups).map(([name,items])=><section className="c-part" key={name}><h3>{name}</h3><ol>{items.map(document=><li key={document.slug}><Link href={document.url}><span>{document.label || (document.kind==="bibliography"?"References":"Front matter")}</span><strong>{document.title}</strong><i aria-hidden="true">↗</i></Link>{document.sections.length?<details><summary>{document.sections.length} sections</summary><ul>{document.sections.map(section=><li key={section.anchor}><Link href={`${document.url}#${section.anchor}`}>{section.number} {section.title}</Link></li>)}</ul></details>:null}</li>)}</ol></section>)}</section>
    <aside className="c-edition-note"><h2>About this web edition</h2><p>The complete publication is converted from the supplied matching final LaTeX with its embedded bibliography. The PDF remains byte-for-byte unchanged. Page furniture and printed contents become accessible web navigation; part dividers are grouped with their chapters.</p><p>In §18.1, the PDF’s unresolved “?? 16.4” is resolved as a link to Assumption 16.4. The <a href="/publications/consciousness/conversion-audit.json">conversion audit</a> records coverage and source hashes. <a href="/publications/consciousness/source-coverage.json">Source-to-web coverage</a> maps the source to this edition.</p><p>{publication.versionNote}</p></aside>
  </article>;
}

