import type {Metadata} from 'next';
import Link from 'next/link';
import katex from 'katex';
import {sealedLeaky as paper,listSealedDocuments} from '@/lib/sealed-leaky';
import {site} from '@/config/site';
import SealedSearch from '@/components/sealed-search';
export const dynamic='force-static';
export const metadata:Metadata={title:'Sealed or Leaky · Complete technical edition',description:paper.description,alternates:{canonical:paper.url,types:{'text/markdown':paper.markdownUrl}},openGraph:{title:'Sealed or Leaky',description:paper.description,url:paper.url,type:'article'}};
export default function SealedEdition(){const documents=listSealedDocuments();return <article className="quantum-reader">
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'ScholarlyArticle',headline:paper.title,description:paper.description,author:{'@type':'Person',name:'Jeremy Rodgers',jobTitle:'Independent Researcher'},url:`${site.url}${paper.url}`,identifier:paper.doiUrl,version:paper.version,inLanguage:'en',isAccessibleForFree:true,encoding:[{ '@type':'MediaObject',encodingFormat:'application/pdf',contentUrl:`${site.url}${paper.pdfUrl}`},{'@type':'MediaObject',encodingFormat:'text/markdown',contentUrl:`${site.url}${paper.markdownUrl}`}],hasPart:documents.map(d=>({'@type':'Chapter',name:d.title,url:`${site.url}${d.url}`}))})}}/>
<header className="quantum-reader-header"><p className="quantum-reader-kicker">Source / readout <span>Follow-on research · Version 3.1</span></p><h1>Sealed or Leaky</h1><p className="quantum-reader-subtitle">The source tetralemma, Bell-certified hidden information, and finite-resource witnesses.</p><p className="mt-5 max-w-3xl leading-relaxed text-mute">Information can remain present in the whole while being inaccessible to an observer inside it. This work turns that distinction into quantitative theorems: how much an initial readout leaves unresolved, when reversible dynamics keep that information sealed, and what finite physical resources can reveal.</p><div className="quantum-reader-downloads"><Link href={paper.articleUrl}>Start with the full explanatory article →</Link><a href={paper.pdfUrl}>PDF</a><a href={paper.texUrl}>LaTeX</a><a href={paper.markdownUrl}>Complete Markdown</a><a href={paper.verificationUrl}>Verification script</a></div><p className="quantum-reader-byline">Jeremy Rodgers · Independent Researcher · Mathematical revision: 21 September 2026<br/><a href={paper.doiUrl}>doi:{paper.doi}</a> · Web edition prepared 1 October 2026</p></header>
<section className="mt-10" aria-labelledby="key-result"><p className="section-label">A quantitative result</p><h2 id="key-result" className="mt-3 text-2xl font-semibold">Bell violation puts a floor under missing information.</h2><div className="sl-formula" dangerouslySetInnerHTML={{__html:katex.renderToString(String.raw`H_{\min}(Z\mid T)\geq-\log_2\!\left(\frac32-\frac{S}{4}\right),\qquad H(Z\mid T)\geq\frac{S-2}{2}`,{displayMode:true,throwOnError:true})}}/><p className="max-w-3xl leading-relaxed text-mute">For CHSH values 2 ≤ S ≤ 4, these bounds are sharp in the conditional no-signalling class. Here T is the nominated initial classical readout and Z the generated outcome record. The source tetralemma connects unresolved outcomes to source incompleteness under definite source outcomes, measurement independence, and no-signalling conditional on T. The complete statements, constructions and proofs are below.</p></section>
<SealedSearch/>
<section id="complete-contents" className="mt-12 scroll-mt-24"><p className="section-label">Complete technical reading edition</p><h2 className="mt-3 text-2xl font-semibold">Every step of the argument.</h2><p className="mt-4 max-w-3xl leading-relaxed text-mute">Read all {documents.length} sections in sequence or enter at the question you need. The edition retains the publication’s numbered statements, full proofs, calculations, tables and bibliography. The <Link href={paper.articleUrl} className="text-glow">companion article</Link> connects the results to the wider framework.</p><ol className="sl-contents">{documents.map(d=><li key={d.slug}><Link href={d.url}><small>{d.label||'PUBLICATION'}</small><strong>{d.title}</strong></Link>{d.sections.length>0&&<details><summary>Explore this section</summary>{d.sections.map(s=><a key={s.anchor} href={`${d.url}#${s.anchor}`}>{s.number} {s.title}</a>)}</details>}</li>)}</ol></section>
<section className="mt-12 card-surface p-6"><h2 className="text-xl font-semibold">From the foundation to information access</h2><p className="mt-3 leading-relaxed text-mute">The seven-paper foundation establishes when readout loss matters, what completion requires, and what internal experiments can identify. Sealed or Leaky adds explicit information bounds and physical access conditions.</p><div className="mt-4 flex flex-wrap gap-5 text-sm text-glow"><Link href="/framework">The framework →</Link><Link href="/papers/non-source-projection-and-internal-identifiability">Paper 6 →</Link><Link href="/papers/bulk-to-brane-projection">Paper 7 →</Link><Link href="/articles/full-shadow-model">The full model →</Link><a href="/sealed-or-leaky/manifest.json">Reading manifest</a></div></section>
</article>;}
