import type {Metadata} from "next";
import Link from "next/link";
import DevelopmentFeature from '@/components/development-feature';
import AgencyFeature from '@/components/agency-feature';
import {agency, listAgencyDocuments} from '@/lib/agency';
import ConsciousnessProgramme from "@/components/consciousness-programme";
import ConsciousnessSearch from "@/components/consciousness-search";
import {researchPapers,listResearchDocuments} from "@/lib/consciousness-research";
import {development, listDevelopmentDocuments} from '@/lib/development';
import {site} from "@/config/site";
export const dynamic="force-static";
export const metadata:Metadata={title:"Boundaries, Development and Agency · Consciousness Research",description:"The full consciousness research programme: SPC-2, robust boundaries, learned interfaces, identified realizations, relational development and reflective agency. Complete articles, mathematics, experiments and proofs.",alternates:{canonical:"/consciousness/research"}};
export default function ResearchProgramme(){const documents=listResearchDocuments();return <article className="c-research-hub">
  <nav className="quantum-reader-breadcrumb" aria-label="Breadcrumb"><Link href="/consciousness">Consciousness</Link><span>/</span><span aria-current="page">The research programme</span></nav>
  <header className="c-research-hero"><p className="c-eyebrow">Shadow Theory / the consciousness programme</p><h1>A perspective.<br/>A boundary.<br/><em>A physical realization.</em></h1><p>Consciousness demands more than a description of behaviour. It demands an account of why a physical organization constitutes a perspective, and a way to determine which organization is actually there.</p><div className="c-actions"><Link className="c-button c-button-primary" href="/consciousness/research/paper-2">Follow the new work ↗</Link><Link className="c-button" href="/consciousness/monograph">Start with the foundation ↗</Link></div></header>
  <ConsciousnessProgramme hub/>
  <AgencyFeature/>
  <DevelopmentFeature/>
  <div className="c-explore-layout"><aside className="c-overview-nav"><p className="c-eyebrow">The connecting argument</p><nav aria-label="Programme sections"><ol><li><a href="#constitution"><span>01</span>Constitution and evidence</a></li><li><a href="#boundary"><span>02</span>The boundary must survive</a></li><li><a href="#learning"><span>03</span>Learning must earn its claims</a></li><li><a href="#realization"><span>04</span>Identification needs interventions</a></li><li><a href="#agency"><span>05</span>Rules can be revised</a></li><li><a href="#reading"><span>06</span>Choose a reading path</a></li></ol></nav><a href="/consciousness/manifest.json">Programme inventory ↗</a><Link href="/consciousness/glossary">Shared vocabulary ↗</Link></aside>
  <div className="c-editorial-body">
    <section id="constitution"><h2>The laws and the evidence belong together.</h2><p>The founding monograph develops the philosophical distinction between awareness and its organized manifestation. SPC-2 then states explicit laws for qualifying perspectives, phenomenal structure and continuation. Its mathematics gives that position a form that can be inspected: physical realization, native predictive organization, joint realization and process identity each do a particular job.</p><p>The next question is unavoidable. How do we know that the boundary we have drawn belongs to the organization itself? How do we recover an interface when the mechanism is opaque? What evidence identifies a realization rather than merely a convenient description of it?</p><p>Papers 2–4 pursue those questions as one connected investigation. A constitutive law, an operational reconstruction and an identification certificate address different steps of the argument. Putting them together makes the framework more exact at each step.</p><p><Link href="/consciousness/monograph/the-shadow-psychophysical-constitution">Read the four constitutive laws ↗</Link></p></section>
    <section id="boundary"><h2>A boundary must survive a change in how we look.</h2><p>Paper 2 begins with a vulnerability in the original boundary construction. A target that is minimal before mixing can lose its apparent dependence after marginalization. The candidate graph can therefore change with the level at which a system is described.</p><p>The response is a deeper operational treatment: reconstruct complete joint experiments, declare the resources available to a severed simulator, and test whether a causal interface preserves the distinctions a surrounding context can expose. Exact masking examples, resource comparisons, quotient and composition results, approximation bounds and identification limits make the proposal concrete.</p><p>This development is visible alongside the preserved monograph. The original boundary law remains the foundation’s original statement; the new work explains where its diagnostics need to be stronger. A robust diagnostic constrains a successor boundary law without selecting a unique phenomenal assignment.</p><p><Link href="/consciousness/research/paper-2">Read: What makes a boundary real? ↗</Link></p></section>
    <section id="learning"><h2>Learning an interface is a sequence of achievements.</h2><p>A representation may have enough capacity to express an adequate interface while the learner never produces it. A learner may produce it while calibration chooses another candidate. A selected candidate may perform well on the declared held-out contexts while a different context exposes its failure.</p><p>Paper 3 separates those events. Its matched study evaluates complete interaction laws across a declared suite of opaque stochastic fixtures. The strongest learner passes 1,063 of 1,152 contexts and 37 of 48 fixtures. The fixture-level path through representational capacity, finite-budget production and selection is 48, then 39, then 37.</p><p>Those distinctions give the numerical results their meaning. The article follows the primary matched comparison, stage-specific failures, uncertainty and composition checks, and the separately labelled retrospective fitting study. It explains both what the learning procedure achieved and exactly which stronger conclusions its protocol cannot carry.</p><p><Link href="/consciousness/research/paper-3">Read: Can an interface be learned? ↗</Link></p></section>
    <section id="realization"><h2>A realization is identified by what interventions reveal.</h2><p>Paper 4 moves from a useful predictive representation to binary coordinate identification under a specified response model. The response family supplies geometric structure: when the prescribed conditions hold, it fixes the binary chart up to coordinate permutation and bit complementation. The paper supplies the identification argument and error certificates.</p><p>It then uses an explicit five-register construction to show why changing a binary encoding is not a harmless relabelling of the declared intervention mechanism. The stochastic continuation results make that obstruction precise. Finally, a bounded computation compares inherited SPC-2 assignments with an official IIT intrinsic-grain search, including its selected grains and numerical outcomes.</p><p>Microchart identification and macrograin selection remain separate tasks. A certificate for coordinates does not automatically choose the scale at which a constitutive law should operate. Keeping that distinction explicit is what lets the comparison teach us something about the two frameworks.</p><p><Link href="/consciousness/research/paper-4">Read: What identifies a realization? ↗</Link></p></section>
    <section id="agency"><h2>An agent can assess the rule that will govern its next choice.</h2><p>Relational development asks how acquired organisation changes future possibilities. Bounded Agency and Reflective Freedom supplies a finite evaluative mechanism: retained commitments enter an assessment, a new rule is installed, and a fresh case demonstrates the changed disposition. Tests of the read and installation routes distinguish that mechanism from an accidental change in output.</p><p>The paper proves a sharp information, mediation and endorsement inequality. In its specified latent-sensor and endorsement model, adaptive inquiry first beats every fixed-count allocation at B = L + 2 paid queries, where L is the first useful calibration count. A faithful native realization then preserves declared operations and information restrictions. Mere recurrence does not establish evaluative agency.</p><p>The website develops every result and proof, then extends the philosophical and technical inquiry into bounded perspective, control, conditioning, provenance and practical freedom. Revising a rule does not by itself mean originating the standards used to assess it, and the connection to SPC-2 retains its stated premises.</p><p><Link href="/consciousness/agency">Read: Agency and Free Will ↗</Link></p></section>
    <section id="reading"><h2>Read for the argument. Stay for every detail.</h2><p>Start with the three lead articles to see how the programme develops. Continue with the <Link href="/consciousness/development">developmental paper</Link> for retained organisation, will, thought, transfer and diagnostic limits, the <Link href="/consciousness/agency">complete agency and free will treatment</Link> for evaluative revision and bounded control, and <Link href="/articles/agency-and-the-constructed-self">Agency and the constructed self</Link> for an accessible introduction to choice, conditioning and RCO. The three companion editions open directly into their full technical investigations: every source section, proof, equation, table, figure, appendix and reference is readable on the site. The developmental edition includes the full text, mathematics and original Figure 1. The section readers retain source numbering so a result can be followed consistently across the website and publication.</p><p>For the philosophical position, begin with the monograph’s <Link href="/consciousness/monograph/the-source-to-experience-problem">source-to-experience problem</Link> and <Link href="/consciousness/monograph/why-a-manifestation-law-is-additional">the argument for an additional manifestation law</Link>. For the new operational work, begin with Paper 2 and continue in order. The <Link href="/consciousness/glossary">glossary</Link>, <Link href="/consciousness/faq">FAQ</Link> and programme search connect the vocabularies.</p></section>
  </div></div>
  <section className="c-research-library"><div className="c-section-heading"><div><p className="c-eyebrow">Five investigations / {documents.length + listDevelopmentDocuments().length + listAgencyDocuments().length} reading sections</p><h2>The publications, open in full.</h2></div></div><ConsciousnessSearch/>{researchPapers.map(p=><div className="c-research-publication" key={p.id}><span className="c-eyebrow">Paper {p.number}</span><div><h3><Link href={p.url}>{p.title}</Link></h3><p>Jeremy Rodgers · Version {p.version}</p><div className="quantum-reader-downloads"><Link href={`${p.url}#complete-contents`}>Complete web edition</Link><a href={p.doiUrl}>doi:{p.doi}</a><a href={p.pdfUrl}>PDF</a><a href={p.markdownUrl}>Markdown</a><a href={p.texUrl}>LaTeX</a></div></div></div>)}<div className="c-research-publication"><span className="c-eyebrow">Development</span><div><h3><Link href={development.url}>{development.fullTitle}</Link></h3><p>Jeremy Rodgers · Revised preprint · 6 October 2026</p><div className="quantum-reader-downloads"><Link href={`${development.url}#complete-contents`}>Full web edition</Link><a href={development.doiUrl}>doi:{development.doi}</a><a href={development.pdfUrl}>PDF</a><a href={development.markdownUrl}>Markdown</a><a href={development.texUrl}>LaTeX</a></div></div></div><div className="c-research-publication"><span className="c-eyebrow">Agency</span><div><h3><Link href={agency.url}>{agency.fullTitle}</Link></h3><p>Jeremy Rodgers · Version 2.0 · 6 October 2026</p><div className="quantum-reader-downloads"><Link href={`${agency.url}#complete-contents`}>Complete web treatment</Link><a href={agency.doiUrl}>doi:{agency.doi}</a><a href={agency.pdfUrl}>PDF</a><a href={agency.markdownUrl}>Website Markdown</a></div></div></div></section>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"CollectionPage",name:"Boundaries, interfaces and realizations",url:`${site.url}/consciousness/research`,hasPart:[...researchPapers,development,agency].map(p=>({"@type":"ScholarlyArticle",name:p.title,url:`${site.url}${p.url}`,identifier:p.doiUrl}))})}}/>
  </article>;}
