import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {sealedLeaky as paper,listSealedDocuments,readSealedHtml} from '@/lib/sealed-leaky';
import {site} from '@/config/site';
export const dynamic='force-static';export const dynamicParams=false;
export function generateStaticParams(){return listSealedDocuments().map(d=>({slug:d.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const d=listSealedDocuments().find(d=>d.slug===slug);if(!d)return{};return{title:`${d.title} · Sealed or Leaky`,description:`${d.title}: complete definitions, calculations and proofs from Sealed or Leaky, version 3.1.`,alternates:{canonical:d.url,types:{'text/markdown':d.markdownUrl}}};}
export default async function Section({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const documents=listSealedDocuments();const index=documents.findIndex(d=>d.slug===slug);const d=documents[index];if(!d)notFound();const previous=documents[index-1],next=documents[index+1];return <article className="quantum-reader sl-reader" id="reader-top">
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Chapter',name:d.title,position:d.order,url:`${site.url}${d.url}`,inLanguage:'en',author:{'@type':'Person',name:'Jeremy Rodgers'},isPartOf:{'@type':'ScholarlyArticle',name:paper.title,url:`${site.url}${paper.url}`,identifier:paper.doiUrl},encoding:{'@type':'MediaObject',encodingFormat:'text/markdown',contentUrl:`${site.url}${d.markdownUrl}`}})}}/>
<nav className="quantum-reader-breadcrumb" aria-label="Breadcrumb"><Link href="/framework">Framework</Link><span>/</span><Link href={paper.url}>Sealed or Leaky</Link><span>/</span><span aria-current="page">{d.label||d.title}</span></nav>
<header className="quantum-reader-header"><p className="quantum-reader-kicker">Sealed or Leaky <span>{d.label||'Publication'}</span></p><h1>{d.title}</h1><p className="quantum-reader-byline">Jeremy Rodgers · Independent Researcher · Version 3.1<br/><a href={paper.doiUrl}>doi:{paper.doi}</a></p><div className="quantum-reader-downloads"><Link href={paper.articleUrl}>Explanatory article</Link><a href={d.markdownUrl}>Section Markdown</a><a href={paper.pdfUrl}>Publication PDF ↗</a><a href={paper.texUrl}>LaTeX source</a></div><div className="quantum-reading-position"><span>Section {index+1} of {documents.length}</span><progress value={index+1} max={documents.length} aria-label={`Section ${index+1} of ${documents.length}`}/></div></header>
<div className="quantum-reading-layout"><aside className="quantum-reader-aside"><details className="quantum-reader-contents" open><summary>On this page <span>↕</span></summary><nav aria-label="Sections on this page"><ol>{d.sections.map(s=><li key={s.anchor} className={s.level>2?'quantum-toc-subsection':''}><a href={`#${s.anchor}`}><span>{s.number}</span> {s.title}</a></li>)}</ol>{!d.sections.length&&<p>{d.title}</p>}</nav></details><details className="sl-all-contents"><summary>All of Sealed or Leaky</summary><nav aria-label="All paper sections">{documents.map(item=><Link key={item.slug} href={item.url} aria-current={item.slug===slug?'page':undefined}>{item.label} · {item.title}</Link>)}</nav></details><nav className="quantum-reader-crosslinks" aria-label="Related reading"><Link href={`${paper.url}#complete-contents`}>Complete contents ↗</Link><Link href={paper.url}>Search the paper ↗</Link><Link href="/articles/full-shadow-model">The full Shadow model ↗</Link><Link href="/framework">The seven-paper foundation ↗</Link><a href={paper.verificationUrl}>Verification script ↗</a></nav><p className="quantum-reader-provenance">Complete publication text with source numbering, proofs, equations and references. The article explains how these results connect.</p></aside><div className="quantum-reader-main"><div className="quantum-publication-text" dangerouslySetInnerHTML={{__html:readSealedHtml(d)}}/><footer className="quantum-reader-end"><span>End of this section</span><a href="#reader-top">Back to top ↑</a></footer></div></div>
<nav className="quantum-chapter-navigation" aria-label="Section navigation">{previous?<Link href={previous.url} rel="prev"><span>← {previous.label}</span><strong>{previous.title}</strong></Link>:<Link href={paper.articleUrl}><span>← Article</span><strong>Why information can remain sealed</strong></Link>}<Link href={`${paper.url}#complete-contents`} className="quantum-chapter-contents-link">All contents</Link>{next?<Link href={next.url} rel="next"><span>{next.label} →</span><strong>{next.title}</strong></Link>:<Link href="/framework"><span>Continue →</span><strong>The wider framework</strong></Link>}</nav>
</article>;}
