import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {getConsciousnessGuide,listConsciousnessGuides} from "@/lib/consciousness";
import {site} from "@/config/site";
import {consciousnessPublication} from "@/config/consciousness";
export const dynamic="force-static";export const dynamicParams=false;
export function generateStaticParams(){return listConsciousnessGuides().map(({slug})=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const guide=getConsciousnessGuide(slug);if(!guide)return {};return {title:guide.title,description:guide.description,alternates:{canonical:`/consciousness/guides/${slug}`},openGraph:{title:guide.title,description:guide.description,url:`/consciousness/guides/${slug}`,type:"article",images:["/publications/consciousness/social.png"]}};}
export default async function GuidePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const guide=getConsciousnessGuide(slug);if(!guide)notFound();const guides=listConsciousnessGuides();const index=guides.findIndex(g=>g.slug===slug);const next=guides[(index+1)%guides.length];
  return <article className="c-guide"><nav className="quantum-reader-breadcrumb" aria-label="Breadcrumb"><Link href="/consciousness">Consciousness</Link><span>/</span><Link href="/consciousness/guides">Guides</Link><span>/</span><span aria-current="page">Guide {String(index+1).padStart(2,"0")}</span></nav><header className="c-guide-header"><p className="c-eyebrow">Explanatory guide {String(index+1).padStart(2,"0")} / SPC-2</p><h1>{guide.title}</h1><p>{guide.description}</p><span className="c-guide-provenance">A web reading guide to the Version 2 publication · <a href={consciousnessPublication.doiUrl}>Source edition ↗</a></span></header><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify([{"@context":"https://schema.org","@type":"Article",headline:guide.title,description:guide.description,url:`${site.url}/consciousness/guides/${slug}`,isBasedOn:consciousnessPublication.doiUrl,about:{"@type":"Book",name:consciousnessPublication.title},publisher:{"@type":"Organization",name:site.name}},{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{name:"Consciousness",item:`${site.url}/consciousness`},{name:"Guides",item:`${site.url}/consciousness/guides`},{name:guide.title,item:`${site.url}/consciousness/guides/${slug}`}].map((item,i)=>({"@type":"ListItem",position:i+1,...item}))}])}}/>
  <div className="c-explore-layout"><aside className="c-overview-nav"><details open><summary>In this guide</summary><nav aria-label="Guide sections"><ol>{guide.sections.map((section,i)=><li key={section.id}><a href={`#${section.id}`}><span>{String(i+1).padStart(2,"0")}</span>{section.title}</a></li>)}</ol></nav></details><Link href="/consciousness/guides">All eight guides ↗</Link><Link href="/consciousness/monograph">The complete monograph ↗</Link><Link href="/consciousness/glossary">Glossary ↗</Link></aside><div className="c-editorial-body">{guide.sections.map(section=><section key={section.id} id={section.id}><h2>{section.title}</h2><div dangerouslySetInnerHTML={{__html:section.html}}/></section>)}</div></div><footer className="c-next-guide"><div><p className="c-eyebrow">Continue exploring</p><Link href={`/consciousness/guides/${next.slug}`}><h2>{next.title}</h2><span>Read the next guide ↗</span></Link></div><Link href="/consciousness/monograph">Inspect the full scientific argument ↗</Link></footer></article>;
}

