import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {site} from "@/config/site";
import {getResearchPaper,getResearchEditorial,listResearchDocuments,researchPapers,renderResearchEditorial} from "@/lib/consciousness-research";
import ConsciousnessProgramme from "@/components/consciousness-programme";
export const dynamic="force-static";export const dynamicParams=false;
export function generateStaticParams(){return researchPapers.map(p=>({paper:p.id}));}
export async function generateMetadata({params}:{params:Promise<{paper:string}>}):Promise<Metadata>{const {paper}=await params;const p=getResearchPaper(paper);if(!p)return {};const article=getResearchEditorial(paper);return {title:article.title,description:article.deck,alternates:{canonical:p.url,types:{"text/markdown":p.markdownUrl}},openGraph:{title:article.title,description:article.deck,url:p.url,type:"article",images:["/publications/consciousness/social.png"]}};}
export default async function ResearchArticle({params}:{params:Promise<{paper:string}>}){const {paper}=await params;const p=getResearchPaper(paper);if(!p)notFound();const article=getResearchEditorial(paper);const documents=listResearchDocuments(paper);
  return <article className="c-guide c-research-article"><nav className="quantum-reader-breadcrumb" aria-label="Breadcrumb"><Link href="/consciousness">Consciousness</Link><span>/</span><Link href="/consciousness/research">Research programme</Link><span>/</span><span aria-current="page">Paper {p.number}</span></nav>
    <header className="c-guide-header"><p className="c-eyebrow">{article.eyebrow}</p><h1>{article.title}</h1><p>{article.deck}</p><span className="c-guide-provenance">Jeremy Rodgers · Independent Researcher · Version {p.version} · <a href={p.doiUrl}>doi:{p.doi} ↗</a></span><div className="c-actions"><a className="c-button c-button-primary" href="#argument">Read the argument ↓</a><a className="c-button" href="#complete-contents">Explore the full technical work ↓</a></div></header>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"ScholarlyArticle",headline:article.title,name:p.title,description:article.deck,url:`${site.url}${p.url}`,identifier:p.doiUrl,author:{"@type":"Person",name:"Jeremy Rodgers"},datePublished:p.date,version:p.version,isPartOf:{"@type":"CollectionPage",name:"The consciousness research programme",url:`${site.url}/consciousness/research`},hasPart:documents.map(d=>({"@type":"Chapter",name:d.title,url:`${site.url}${d.url}`})),encoding:[{encodingFormat:"application/pdf",contentUrl:`${site.url}${p.pdfUrl}`},{encodingFormat:"text/markdown",contentUrl:`${site.url}${p.markdownUrl}`}].map(e=>({"@type":"MediaObject",...e}))})}}/>
    <div className="c-explore-layout" id="argument"><aside className="c-overview-nav"><p className="c-eyebrow">The argument</p><nav aria-label="Article sections"><ol>{article.sections.map((s,i)=><li key={s.id}><a href={`#${s.id}`}><span>{String(i+1).padStart(2,"0")}</span>{s.title}</a></li>)}</ol></nav><a href="#complete-contents">Every result, proof and appendix ↓</a><a href={p.pdfUrl}>Publication PDF ↗</a><a href={p.markdownUrl}>Complete paper Markdown ↗</a><Link href="/consciousness/research">The research programme ↗</Link></aside><div className="c-editorial-body">{article.sections.map(s=><section id={s.id} key={s.id}><h2>{s.title}</h2><div dangerouslySetInnerHTML={{__html:renderResearchEditorial(s.html)}}/></section>)}</div></div>
    <section className="c-research-contents" id="complete-contents"><div className="c-section-heading"><div><p className="c-eyebrow">Paper {p.number} / the complete technical work</p><h2>Inspect every step.</h2></div><a href={p.markdownUrl}>Read as one Markdown document ↗</a></div><p className="c-programme-intro">Follow the investigation through its definitions, derivations, proofs and results. Every section and appendix is available here, with the publication’s numbering and references.</p><ol>{documents.map(d=><li key={d.slug}><Link href={d.url}><span>{d.label||d.kind}</span><strong>{d.title}</strong><i aria-hidden="true">↗</i></Link>{d.sections.length>1&&<details><summary>Sections in this chapter</summary><ul>{d.sections.map(s=><li key={s.anchor}><Link href={`${d.url}#${s.anchor}`}>{s.number} {s.title}</Link></li>)}</ul></details>}</li>)}</ol></section>
    <aside className="c-edition-note" id="publication"><h2>Publication and research materials</h2><p>{p.title}. Jeremy Rodgers. Version {p.version}. <a href={p.doiUrl}>doi:{p.doi}</a>.</p><p><a href={p.pdfUrl}>Matching PDF</a> · <a href={p.texUrl}>Original LaTeX</a> · <Link href={`/papers/${p.paperSlug}`}>Publication record</Link> · <a href="/consciousness/manifest.json">Full programme inventory</a></p><p>The web edition includes the complete argument and all results reported in the manuscript. Separate research archives and reports cited by the authors are described in the source materials sections; those external files were not supplied with this edition.{p.number===4?" The separate supporting-deposit identifier has not been provided; the DOI above identifies this paper.":""}</p></aside>
    <ConsciousnessProgramme compact/>
  </article>;
}
