import Link from "next/link";
import { researchPapers } from "@/lib/consciousness-research";

export default function ConsciousnessProgramme({compact=false,hub=false}:{compact?:boolean;hub?:boolean}) {
  return <section className={`c-programme ${compact?"c-programme-compact":""}`} aria-labelledby="programme-title">
    <div className="c-section-heading"><div><p className="c-eyebrow">One programme / six publications</p><h2 id="programme-title">{hub?<>One foundation.<br/>Five connected investigations.</>:<>From a perspective<br/>to its physical realization.</>}</h2></div>{!hub&&<Link href="/consciousness/research">Explore the research programme ↗</Link>}</div>
    {!compact&&<p className="c-programme-intro">SPC-2 gives the framework its constitutive laws. Three connected investigations put its boundaries, learning procedures and realization criteria under precise mathematical pressure. The developmental investigation asks how retained relations shape subsequent interpretation, reasoning and action. Bounded agency then makes the assessment and revision of decision rules explicit, with exact information and inquiry limits.</p>}
    <div className="c-programme-grid"><Link href="/consciousness/monograph"><span className="c-eyebrow">01 / Foundation</span><h3>How does awareness<br/>become a lived world?</h3><p>The philosophy, physics and mathematics of Shadow Theory and the SPC-2 constitution.</p><span className="c-programme-link">The complete monograph ↗</span></Link>{researchPapers.map(p=><Link key={p.id} href={p.url}><span className="c-eyebrow">0{p.number} / {p.step}</span><h3>{p.shortTitle}</h3><p>{p.deck}</p><span className="c-programme-link">Read the full investigation ↗</span></Link>)}<Link href="/consciousness/development"><span className="c-eyebrow">05 / Development</span><h3>How does experience shape what comes next?</h3><p>Retained relations, continuation, transfer and diagnostic limits, with a conditional native incorporation witness.</p><span className="c-programme-link">Read the full investigation ↗</span></Link><Link href="/consciousness/agency"><span className="c-eyebrow">06 / Agency and free will</span><h3>Can an agent revise the rules by which it chooses?</h3><p>Evaluative revision on fresh cases, sharp information limits, adaptive inquiry and faithful realization.</p><span className="c-programme-link">The complete argument and mathematics ↗</span></Link></div>
  </section>;
}
