import Link from "next/link";
import { site } from "@/config/site";
import { getResearchChapterIntro,getResearchPaper,listResearchDocuments,readResearchHtml,type ResearchDocument } from "@/lib/consciousness-research";
import ConsciousnessSearch from "./consciousness-search";

export default function ConsciousnessResearchReader({document}:{document:ResearchDocument}) {
  const paper=getResearchPaper(document.paperId)!;
  const documents=listResearchDocuments(paper.id);const index=documents.findIndex(d=>d.slug===document.slug);
  const previous=documents[index-1], next=documents[index+1];const intro=getResearchChapterIntro(document);
  return <article className="quantum-reader c-reader c-research-reader" id="reader-top">
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Chapter",name:document.title,position:document.order,url:`${site.url}${document.url}`,inLanguage:"en",author:{"@type":"Person",name:"Jeremy Rodgers"},datePublished:paper.date,isPartOf:{"@type":"ScholarlyArticle",name:paper.title,url:`${site.url}${paper.url}`,identifier:paper.doiUrl},encoding:{"@type":"MediaObject",encodingFormat:"text/markdown",contentUrl:`${site.url}${document.markdownUrl}`}})}}/>
    <nav className="quantum-reader-breadcrumb" aria-label="Breadcrumb"><Link href="/consciousness">Consciousness</Link><span>/</span><Link href="/consciousness/research">Research</Link><span>/</span><Link href={paper.url}>Paper {paper.number}</Link><span>/</span><span aria-current="page">{document.label||document.title}</span></nav>
    <header className="quantum-reader-header"><p className="quantum-reader-kicker">Paper {paper.number} · {document.label}<span>{paper.step}</span></p><h1>{intro?.title||document.title}</h1>{intro&&<p className="quantum-reader-subtitle">{intro.standfirst}</p>}<p className="quantum-reader-byline">Jeremy Rodgers · Independent Researcher<br/><a href={paper.doiUrl}>doi:{paper.doi}</a> · Version {paper.version}</p><div className="quantum-reader-downloads"><Link href={paper.url}>Read the article</Link><a href={document.markdownUrl}>Section Markdown</a><a href={paper.pdfUrl}>Publication PDF ↗</a><a href={paper.texUrl}>LaTeX source</a></div><div className="quantum-reading-position"><span>Section {index+1} of {documents.length}</span><progress max={documents.length} value={index+1} aria-label={`Section ${index+1} of ${documents.length}`}/></div></header>
    <div className="quantum-reading-layout"><aside className="quantum-reader-aside"><details className="quantum-reader-contents" open><summary>On this page <span>↕</span></summary><nav aria-label="Sections on this page"><ol>{document.sections.map(s=><li key={s.anchor} className={s.level>2?"quantum-toc-subsection":""}><a href={`#${s.anchor}`}><span>{s.number}</span> {s.title}</a></li>)}</ol>{!document.sections.length&&<p>{document.title}</p>}</nav></details><details className="c-all-contents"><summary>All of Paper {paper.number}</summary><nav aria-label="All paper sections"><ol>{documents.map(d=><li key={d.slug}><Link href={d.url} aria-current={d.slug===document.slug?"page":undefined}>{d.label} · {d.title}</Link></li>)}</ol></nav></details><details className="c-all-contents"><summary>Search the programme</summary><ConsciousnessSearch/></details><nav className="quantum-reader-crosslinks" aria-label="Related reading"><Link href={`${paper.url}#complete-contents`}>Paper contents ↗</Link><Link href="/consciousness/research">The research programme ↗</Link><Link href="/consciousness/monograph">The founding monograph ↗</Link><Link href="/consciousness/glossary">Glossary ↗</Link></nav><p className="quantum-reader-provenance">The complete technical argument, with the publication’s original numbering, proofs, equations and references. Introductions and navigation connect it to the wider programme.</p></aside>
    <div className="quantum-reader-main"><div className="quantum-publication-text" dangerouslySetInnerHTML={{__html:readResearchHtml(document)}}/><footer className="quantum-reader-end"><span>End of this section</span><a href="#reader-top">Back to top ↑</a></footer></div></div>
    <nav className="quantum-chapter-navigation" aria-label="Section navigation">{previous?<Link href={previous.url} rel="prev"><span>← {previous.label}</span><strong>{previous.title}</strong></Link>:<Link href={paper.url}><span>← Article</span><strong>{paper.shortTitle}</strong></Link>}<Link href={`${paper.url}#complete-contents`} className="quantum-chapter-contents-link">All contents</Link>{next?<Link href={next.url} rel="next"><span>{next.label} →</span><strong>{next.title}</strong></Link>:<Link href="/consciousness/research"><span>The next question →</span><strong>Continue through the programme</strong></Link>}</nav>
  </article>;
}
