import Link from "next/link";
import { site } from "@/config/site";
import { consciousnessPublication as publication } from "@/config/consciousness";
import { getConsciousnessAdjacent, listConsciousnessDocuments, readConsciousnessHtml, type ConsciousnessDocument } from "@/lib/consciousness";
import ConsciousnessSearch from "./consciousness-search";
export default function ConsciousnessReader({document}:{document:ConsciousnessDocument}) {
  const documents = listConsciousnessDocuments(); const adjacent = getConsciousnessAdjacent(document.slug);
  const source = (document as ConsciousnessDocument & {source?:{pdfPage?:number;pdfEndPage?:number}}).source;
  const structured = [{"@context":"https://schema.org","@type":"Chapter",name:document.title,position:document.order,url:`${site.url}${document.url}`,inLanguage:"en",author:{"@type":"Person",name:publication.author},datePublished:publication.published,isPartOf:{"@type":"Book",name:publication.title,url:`${site.url}${publication.webUrl}`,identifier:publication.doiUrl,bookEdition:"Version 2 — publication edition"},encoding:{"@type":"MediaObject",encodingFormat:"text/markdown",contentUrl:`${site.url}${document.markdownUrl}`}},{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{name:"Consciousness",item:`${site.url}/consciousness`},{name:"Monograph",item:`${site.url}/consciousness/monograph`},{name:document.title,item:`${site.url}${document.url}`}].map((item,i)=>({"@type":"ListItem",position:i+1,...item}))}];
  return <article className="quantum-reader c-reader" id="reader-top">
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured)}}/>
    <nav className="quantum-reader-breadcrumb" aria-label="Breadcrumb"><Link href="/consciousness">Consciousness</Link><span>/</span><Link href="/consciousness/monograph">Monograph</Link><span>/</span><span aria-current="page">{document.label || document.title}</span></nav>
    <header className="quantum-reader-header"><p className="quantum-reader-kicker">{document.label || "Front matter"}<span>SPC-2 · Version 2</span></p><h1>{document.title}</h1><p className="quantum-reader-byline">{publication.author} · {publication.authorRole}<br/>{publication.dateLabel} · <a href={publication.doiUrl}>doi:{publication.doi}</a></p><div className="quantum-reader-downloads" aria-label="Publication formats"><a href={`${publication.pdfUrl}${source?.pdfPage ? `#page=${source.pdfPage}` : ""}`}>Publication PDF{source?.pdfPage ? ` · p. ${source.pdfPage}` : ""} ↗</a><a href={document.markdownUrl}>Chapter Markdown</a><a href={publication.texUrl}>Original LaTeX</a><Link href={`/papers/${publication.paperSlug}`}>Publication record</Link></div><div className="quantum-reading-position"><span>Reading position {document.order} of {documents.length}</span><progress max={documents.length} value={document.order} aria-label={`Reading position ${document.order} of ${documents.length}`}/></div></header>
    <div className="quantum-reading-layout"><aside className="quantum-reader-aside"><details className="quantum-reader-contents" open><summary>On this page <span>↕</span></summary><nav aria-label="Sections on this page"><ol>{document.sections.map(section=><li key={section.anchor} className={section.level>2?"quantum-toc-subsection":""}><a href={`#${section.anchor}`}><span>{section.number}</span> {section.title}</a></li>)}</ol>{!document.sections.length?<p>Complete {document.kind === "bibliography" ? "bibliography" : "front matter"} below.</p>:null}</nav></details>
      <details className="c-all-contents"><summary>Browse the entire book</summary><nav aria-label="All book chapters"><ol>{documents.map(item=><li key={item.slug}><Link href={item.url} aria-current={item.slug===document.slug?"page":undefined}>{item.label ? `${item.label} · ` : ""}{item.title}</Link></li>)}</ol></nav></details><details className="c-all-contents"><summary>Search the monograph & guides</summary><ConsciousnessSearch/></details><nav className="quantum-reader-crosslinks" aria-label="Related reading"><Link href="/consciousness/monograph">Full monograph contents ↗</Link><Link href="/consciousness/guides">Explanatory guides ↗</Link><Link href="/consciousness/glossary">Glossary ↗</Link><Link href="/consciousness/faq">FAQ ↗</Link></nav><p className="quantum-reader-provenance">Fixed publication text. Original scientific statements, proofs, equations and citations. Navigation and page layout adapted for the web.</p></aside>
      <div className="quantum-reader-main"><div className="quantum-publication-text" dangerouslySetInnerHTML={{__html:readConsciousnessHtml(document)}}/>{document.slug==="completion-invariance-and-empirical-conservativity"?<aside className="quantum-source-note"><span className="quantum-source-note-label">Web-edition correction</span><p>The unresolved “?? 16.4” in the archival PDF’s §18.1 is linked here to <Link href="/consciousness/monograph/endogenous-predictive-structure-across-horizons#ass:spc2-congruence">Assumption 16.4</Link>. The supplied PDF is unchanged.</p></aside>:null}<footer className="quantum-reader-end"><span>End of this section</span><a href="#reader-top">Back to top ↑</a></footer></div></div>
    <nav className="quantum-chapter-navigation" aria-label="Chapter navigation">{adjacent.previous?<Link href={adjacent.previous.url} rel="prev"><span>← Previous · {adjacent.previous.label || "Front matter"}</span><strong>{adjacent.previous.title}</strong></Link>:<div/>}<Link href="/consciousness/monograph" className="quantum-chapter-contents-link">All contents</Link>{adjacent.next?<Link href={adjacent.next.url} rel="next"><span>Next · {adjacent.next.label || "Front matter"} →</span><strong>{adjacent.next.title}</strong></Link>:<div/>}</nav>
  </article>;
}

