import type { Metadata } from "next";
import Link from "next/link";
import ConsciousnessNetwork from "@/components/consciousness-network";
import { getConsciousnessEditorial, listConsciousnessGuides } from "@/lib/consciousness";
import { consciousnessPublication as publication } from "@/config/consciousness";
import { site } from "@/config/site";
export const dynamic = "force-static";
export const metadata: Metadata = {title:"Consciousness: SPC-2 and the Source-to-Experience Problem",description:"From awareness to a lived world. Explore Shadow Theory’s laws of perspective, phenomenal structure and experiential continuity, and read the complete SPC-2 monograph.",alternates:{canonical:"/consciousness"},openGraph:{title:"Consciousness. From awareness to a lived world.",url:"/consciousness",images:["/publications/consciousness/social.png"]}};
export default function ConsciousnessOverview() {
  const overview = getConsciousnessEditorial().overview; const guides = listConsciousnessGuides();
  return <article className="c-overview">
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Article",headline:overview.title,description:overview.description,url:`${site.url}/consciousness`,author:{"@type":"Person",name:"Jeremy Rodgers"},about:{"@type":"Book",name:publication.title,identifier:publication.doiUrl},isPartOf:{"@type":"WebSite",url:site.url}})}}/>
    <header className="c-hero"><p className="c-eyebrow"><span className="c-status-dot"/> Shadow Theory / Consciousness / SPC-2</p><h1>Consciousness.</h1><p className="c-hero-line">From awareness<br className="c-mobile-break"/> to a <em>lived world.</em></p><div className="c-hero-bottom"><p className="c-hero-description">What makes a physical organization a perspective?<br className="c-desktop-break"/> Shadow Theory proposes that organization shapes the manifestation of awareness. SPC-2 gives that proposal explicit laws.</p><span className="c-edition">VERSION 2<br/>20 SEPTEMBER 2026</span></div>
      <div className="c-actions"><Link className="c-button c-button-primary" href="/consciousness/monograph">Read the complete monograph <span>↗</span></Link><a className="c-button" href="#explore">Explore the model <span>↓</span></a><a className="c-text-link" href={publication.doiUrl}>Publication / DOI ↗</a></div><p className="c-status">Candidate internal constitutive resolution under declared assumptions.</p>
    </header>
    <ConsciousnessNetwork/>
    <div className="c-edition-strip"><span>5 parts</span><span>25 chapters</span><span>6 appendices</span><span>Complete proofs & bibliography</span><a href={publication.pdfUrl}>Publication PDF ↗</a></div>
    <div className="c-explore-layout" id="explore"><aside className="c-overview-nav"><p className="c-eyebrow">Inside the model</p><nav aria-label="Overview sections"><ol>{overview.sections.map((section,index)=><li key={section.id}><a href={`#${section.id}`}><span>{String(index+1).padStart(2,"0")}</span>{section.title}</a></li>)}</ol></nav><Link href="/consciousness/glossary">Glossary ↗</Link><Link href="/consciousness/faq">Questions & answers ↗</Link></aside><div className="c-editorial-body">{overview.sections.map((section,index)=><section id={section.id} key={section.id}><p className="c-section-number">{String(index+1).padStart(2,"0")} / THE MODEL</p><h2>{section.title}</h2><div dangerouslySetInnerHTML={{__html:section.html}}/></section>)}</div></div>
    <section className="c-guides-preview"><div className="c-section-heading"><div><p className="c-eyebrow">Eight ways into the argument</p><h2>Follow your question.</h2></div><Link href="/consciousness/guides">All explanatory guides ↗</Link></div><div className="c-guide-grid">{guides.map((guide,index)=><Link key={guide.slug} href={`/consciousness/guides/${guide.slug}`}><span className="c-eyebrow">GUIDE {String(index+1).padStart(2,"0")}</span><h3>{guide.title}</h3><p>{guide.description}</p><span className="c-guide-arrow" aria-hidden="true">↗</span></Link>)}</div></section>
    <footer className="c-publication-footer"><p className="c-eyebrow">The publication edition</p><h2>{publication.title}</h2><p>Jeremy Rodgers · Independent Researcher · Version 2 · 20 September 2026</p><div className="c-actions"><Link className="c-button c-button-primary" href="/consciousness/monograph">Read the full work ↗</Link><a className="c-button" href={publication.pdfUrl}>Download PDF ↗</a><a className="c-text-link" href={publication.doiUrl}>doi:{publication.doi}</a></div><p className="c-history-note">Version 2 supersedes the earlier Consciousness Field account. The current formulation is SPC-2, presented in <em>Shadow Theory and Consciousness</em>.</p></footer>
  </article>;
}
